import Head from "next/head";
import React from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
  AiFillHeart,
} from "react-icons/ai";
import Image from "next/image";
import harsh from "../public/harsh.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";
import CV from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Next JS portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-6 text-black dark:bg-gray-900 dark:text-white">
        <section className="min-h-screen ">
          <nav className="py-10 mb-4 flex justify-between">
            <h1 className=" font-bold ">by HRS</h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-xl">
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-6 py-1.5 rounded-md ml-4"
                  href={CV}
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center mb-10 ">
            <h2 className=" text-4xl py-2 text-teal-600 font-medium">
              Harsh Singh
            </h2>
            <h3 className="text-md py-2 dark:text-slate-400">
              Developer and designer.
            </h3>
            <p className=" text-sm py-2 leading-8 text-gray-800 md:px-20 lg:20-px dark:text-slate-500">
              If you need to use a one-off color value that doesn’t make sense
              to include in your theme, use square brackets to generate a
              property on the fly using any arbitrary value
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-16 text-teal-500 ">
            <a href="https://www.linkedin.com/in/harshstag/" target="_blank">
              <AiFillLinkedin />
            </a>

            <a href="https://github.com/Harshstag" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/harshstag/" target="_blank">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden">
            <Image src={harsh} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className=" lg:px-40">
            <h1 className="text-2xl   text-teal-500 py-4 mt-10">
              Services I offer
            </h1>
            <p className=" text-md py-4 leading-8 text-gray-800 dark:text-slate-500">
              You can also use variant modifiers to target media queries like
              responsive breakpoints, dark mode,{" "}
              <span className="text-teal-500">Click Here </span>
              prefers-reduced-motion, and more. For example, use
              md:text-green-600 to apply the text-green-600 utility at only
              medium screen sizes and above.
            </p>
            <p className=" text-md py-4 leading-8 text-gray-800 dark:text-slate-500">
              You can also use variant modifiers to target media queries like
              responsive breakpoints, dark mode,{" "}
              <span className="text-teal-500">Click Here </span>
              prefers-reduced-motion, and more. For example, use
              md:text-green-600 to apply the text-green-600 utility at only
              medium screen sizes and above.
            </p>
          </div>
          <div className="lg:px-40 lg:flex lg:gap-10">
            <div className=" text-center bg-gradient-to-b from-teal-500 to-slate-200 w-100 h-200 shadow-2xl p-10 rounded-xl my-10">
              <div className="text-center px-20">
                <a href="https://github.com/Harshstag" target="_blank">
                  <Image src={design} alt="img" />
                </a>
              </div>

              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegate design suited for your needs design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Canva</p>
              <p className=" text-gray-800 py-1">Primerpro</p>
            </div>
            <div className="text-center bg-gradient-to-b from-teal-500 to-slate-200 w-100 h-200 shadow-2xl p-10 rounded-xl my-10">
              <div className="text-center px-20">
                <Image src={consulting} alt="img" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegate design suited for your needs design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Canva</p>
              <p className=" text-gray-800 py-1">Primerpro</p>
            </div>
            <div className=" text-center bg-gradient-to-b from-teal-500 to-slate-200 w-100 h-200 shadow-2xl p-10 rounded-xl my-10">
              <div className="text-center px-20">
                <Image src={code} alt="img" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegate design suited for your needs design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I use</h4>
              <p className=" text-gray-800 py-1">Photoshop</p>
              <p className=" text-gray-800 py-1">Canva</p>
              <p className=" text-gray-800 py-1">Primerpro</p>
            </div>
          </div>
        </section>
        <section>
          <div className="lg:px-40">
            <h3 className="text-2xl py-1  text-teal-500 ">Portofolio</h3>
            <p className=" text-md py-4 leading-8 text-gray-800 dark:text-slate-500">
              You can also use variant modifiers to target media queries like
              responsive breakpoints, dark mode,{" "}
              <span className="text-teal-500">Click Here </span>
              prefers-reduced-motion, and more. For example, use
              md:text-green-600 to apply the text-green-600 utility at only
              medium screen sizes and above.
            </p>
          </div>
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap lg:px-40">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
